### ISSUE TITLE
Decide on a standard lesson format & update lesson archetype files

### ISSUE THREAD

**Issue by titaniumbones** [code-at-the-edge/curriculum-materials#10]
They're not very well thought out & need some improvement.  cf. #7 as well. 

-

**Comment by dcwalk** [comment]
This was partially addressed in #12, but I expect some updates next week once all the material has been looked at! 

Let's keep this open until then :))

**Comment by dcwalk** [comment]
We did the lessons in #21! We have a general format updated there too! Closing for now
