### ISSUE TITLE
template tags don't render in `instructions.md` and `teaher.md`

### ISSUE THREAD

**Issue by titaniumbones** [code-at-the-edge/curriculum-materials#11]
We currently acquire the text for the instructions div with 

`{{path.Join .File.Dir "instructions.md" | readFile | markdownify | safeHTML}}`

Unfortunatley markdownify doesn't evaluate template tags. Can we do anything about this?

**Comment by dcwalk** [comment]
What template tags are you worried about? Now that we've changed how that partial works, I think just `teaching.md` is impacted.

Is this still a concern @titaniumbones ?

**Comment by titaniumbones** [comment]
appears to be resolved in current master.
