### ISSUE TITLE
Add env variables to install script

### ISSUE THREAD

**Issue by titaniumbones** [code-at-the-edge/curriculum-materials#29]
Would be nice to allow customization of a few things i n the install script:

- rpi password
- jsbin user/pass/db
- mysql root pass
- rpi hostname
- rpi /etc/hosts values? 
- etc.

just a quick default list, sorry not more detailed!

**Comment by dcwalk** [comment]
Our initial set of scripts have env variables: https://github.com/code-at-the-edge/curriculum-materials/tree/master/scripts, however we need to finish writing them, closing this issue in favour of tracking here: #49
