### ISSUE TITLE
grab Internet in a Box & deploy on an rPi, maybe on the plane

### ISSUE THREAD

**Issue by titaniumbones** [code-at-the-edge/curriculum-materials#34]
https://github.com/iiab/iiab

**Comment by dcwalk** [comment]
We should buy another case then, looking at [specs](https://meta.wikimedia.org/wiki/Internet-in-a-Box/Buy) of pre-configured ones, 32GB seems fine.
The size of downloads makes me think we should aim to set this up before the weekend.

It also [sets up a hotspot and allows serving local content](https://github.com/iiab/iiab/wiki/IIAB-Installation#local-content)--maybe we could actually add all the teaching materials to a box?

**Comment by dcwalk** [comment]
We tested this out and decided not to go ahead with this. Closing for now, we can reopen/make a new one if we revisit in the future (edit: and probably in https://github.com/code-at-the-edge/project/)
