### ISSUE TITLE
get travis to actually deploy

### ISSUE THREAD

**Issue by titaniumbones** [code-at-the-edge/curriculum-materials#4]
for some reason travis is not actually ubilding on tjis repo. No idea why!

**Comment by dcwalk** [comment]
@titaniumbones Travis appears to be deploying -- see the latest change reflected in a successful build here: https://travis-ci.org/code-at-the-edge/curriculum-materials/builds/470861686

and it is live on gh pages: https://code-at-the-edge.github.io/curriculum-materials/
(updated `--navigateToChanged` flag)

However, I think there is probably some benefit on having builds triggered on PRs/not just master branch!

We could remove this chunk from .travis.yml:
```
branches:
  only:
    - master
```

**Comment by dcwalk** [comment]
I removed the chunk above in https://github.com/code-at-the-edge/curriculum-materials/pull/16, and it is live on the site, so I'm closing this as done!
