### ISSUE TITLE
move nav to top bar

### ISSUE THREAD

**Issue by titaniumbones** [code-at-the-edge/curriculum-materials#5]
Would rather have a breadcrumb nav in top par to givem roe spae to side-by-side views 

- [ ] rewrite menu & add to header 
- [ ] remove aside from `layouts/_default/baseof.html`

**Comment by dcwalk** [comment]
We've actually wound up using side and top nav for different things. I'm closing this as `wontfix`, because a re-implementation in jekyll (#48 ) may resurface this question in a different way and should be re-ticketed at that time
