### ISSUE TITLE
schedule docsprint

### ISSUE THREAD

**Issue by titaniumbones** [code-at-the-edge/curriculum-materials#53]
Would be cool to do a post-trip sprint of some kind? We need docs for various audiences:
- ourselves (!)
- possible collaborators who might bei nterested in contributing to/critiquing our work on GH (local & remote)
- on-the-ground teachers in the ocntexts we visit (forn ow at least this means KGBV)
- students themselves

**Comment by dcwalk** [comment]
Can we move this to the project repo? This seems like a better fit there than the curriculum materials repo

**Comment by dcwalk** [comment]
Closing as I've refiled here: https://github.com/code-at-the-edge/project/issues/27
